# Generated by Django 3.0.8 on 2020-07-23 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbitros',
            fields=[
                ('CodigoArb', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('DNI', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('Idequipo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('razon_social', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Junta_directiva',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('Idequipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Equipos')),
            ],
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('Idliga', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('razon_social', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vocal',
            fields=[
                ('CodigoVoc', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('DNI', models.IntegerField()),
                ('Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Junta_directiva')),
            ],
        ),
        migrations.CreateModel(
            name='Tesorero',
            fields=[
                ('CodigoTes', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('DNI', models.IntegerField()),
                ('Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Junta_directiva')),
            ],
        ),
        migrations.CreateModel(
            name='Secretario',
            fields=[
                ('CodigoSec', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('DNI', models.IntegerField()),
                ('Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Junta_directiva')),
            ],
        ),
        migrations.CreateModel(
            name='Presidente',
            fields=[
                ('CodigoPre', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('DNI', models.IntegerField()),
                ('Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Junta_directiva')),
            ],
        ),
        migrations.CreateModel(
            name='Partidos',
            fields=[
                ('Idpartido', models.IntegerField(primary_key=True, serialize=False)),
                ('estadio', models.CharField(max_length=20)),
                ('EquipoV', models.IntegerField()),
                ('EquipoL', models.IntegerField()),
                ('fecha', models.CharField(max_length=10)),
                ('CodigoArb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Arbitros')),
                ('Idliga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Liga')),
            ],
        ),
        migrations.AddField(
            model_name='junta_directiva',
            name='Idliga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Liga'),
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('CodigoJug', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('DNI', models.IntegerField()),
                ('Idequipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Equipos')),
            ],
        ),
        migrations.CreateModel(
            name='Goles',
            fields=[
                ('Idgol', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=10)),
                ('CodigoJug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Jugador')),
                ('Idpartido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Partidos')),
            ],
        ),
        migrations.AddField(
            model_name='equipos',
            name='Idliga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Liga'),
        ),
        migrations.CreateModel(
            name='DirectorT',
            fields=[
                ('CodigoDir', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('DNI', models.IntegerField()),
                ('Idequipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Equipos')),
            ],
        ),
    ]
